language: python
python: 
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader punkt averaged_perceptron_tagger 
script:
  - python test.py