language: python
python: 
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo python -m nltk.downloader -d /usr/share/nltk_data all 
script:
  - python test.py